name: Download AutoHosts.txt  
  
on:  
  push:  
    branches: [ main ]  
  schedule:  
    - cron: '0 0 * * *'  # 每天午夜运行一次  
  workflow_dispatch:  # 允许手动触发  
  
jobs:  
  download-hosts:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  
        with:  
          fetch-depth: 0  # 获取整个仓库的历史记录，以便能够推送更改  
          ref: master  # 切换到master分支  
  
      - name: Download AutoHosts.txt  
        run: |  
          wget http://47.97.11.31:6008/hosts.txt -O AutoHosts.txt  
  
      - name: Commit and push if AutoHosts changed  
        run: |  
          git config --local user.email "action@github.com"  
          git config --local user.name "GitHub Action"  
          git add AutoHosts.txt  
          if [ -z "$(git status --porcelain hosts.txt)" ]; then  
            echo "No changes to hosts.txt"  
          else  
            git commit -m "Update hosts.txt"  
            git push origin HEAD:master  # 推送到master分支  
          fi
