name: Download GithubHosts.txt
  
on:  
  push:  
    branches: [ main ]  
  schedule:  
    - cron: '0 0 * * *'  # 每天午夜运行一次  
  workflow_dispatch:  # 允许手动触发  
  
jobs:  
  download-GithubHosts:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  
        with:  
          fetch-depth: 0  # 获取整个仓库的历史记录，以便能够推送更改  
          ref: master  # 切换到master分支  
            
      - name: Download GithubHosts.txt  
        run: |  
         wget "https://raw.githubusercontent.com/ineo6/hosts/refs/heads/master/hosts" -O GithubHosts.txt  
            
      - name: Commit and push if GithubHosts.txt changed  
        run: |  
          git config --global user.name 'jackloves111'  
          git config --global user.email '1056349644@qq.com'  
          git add GithubHosts.txt  
          if [ -z "$(git status --porcelain GithubHosts.txt)" ]; then  
            echo "GithubHosts.txt 未变动"  
          else  
            git commit -m "更新 GithubHosts.txt"  
            git push origin HEAD:master  # 推送到master分支  
          fi
